### PR TITLE
Never assume statistics

### PR DESCRIPTION
**Pull request by jpivarski**
Imposes a rule that Histogrammar should never assume things like sqrt(N) errors in Count or sqrt(p*(1-p)/N) errors in Fraction. We can provide options (a standard suite of lambda functions) but the user must explicitly name one when constructing a plot--- the user must be completely in control of statistical choices.

However, even the problem of providing choices is overwhelming.
  - https://www.ine.pt/revstat/pdf/rs120203.pdf provides 19 choices for confidence intervals on the Poisson mean
  - http://projecteuclid.org/download/pdf_1/euclid.ss/1009213286 and https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval provides a half dozen for the Binomial mean

A reasonable suite should at least provide the Clopper-Pearson ("exact") bounds and let the user delve into the others on his or her own time. This pull request includes _commented out_ Wald (normal, naive) and Wilson (closed-form estimates). The Pearson bounds would require special functions, unwanted dependencies for both Scala and Python.

I've commented out the Wald and Wilson functions because we should get on top of this and figure out how we want to provide statistics in a uniform way, if at all. New dependencies have to be better justified, and possibly segregated into a separate JAR.

This version at least asks the user for a confidence interval function when making error bars. For expedience, you can supply `{(n, d, z) => val p = n/d; val err = Math.sqrt(p*(1.0 - p)/d); (p-z*err, p, p+z*err)}` to this function to get naive error bars.

I also changed the name of `Selected.value` to `Selected.cut` to reduce the anonymous `values` all over the code. `cut` is more clear and will avoid some compilable errors.

### CODE REVIEW

**Comment by cranmer** [comment]
Nice that you are not hard coding the statistics here 👍 
Will you provide a default? 

Note on Binomial there is also this paper:
http://inspirehep.net/record/851171

**Comment by jpivarski** [comment]
Thanks! (I know two of the authors...)

The functions that would make a plot with error bars take a lambda for calculating them, and I wanted to provide a few standard options so that users don't have to write the lambdas for the most common cases. I implemented Wald (what everyone does, has bad properties) and Wilson (closed-form, better properties), but found Wilson's Poisson confidence interval bounds have the wrong _order_ for Poisson means below 1, so it's obviously an extrapolation.

After digging around this weekend, it looks like the appropriate default to provide would be Clopper-Pearson, but calculating this for Poisson and Binomial will require special functions and therefore dependencies.

I've put this aside to think more about what the scope of Histogrammar ought to be. It's supposed to aggregate, nothing more, and leave plotting to existing graphics libraries. The same could be said for statistics: it aggregates the data, something else analyzes it. Implementing several confidence interval methods and bringing in dependencies just for them is a slippery slope toward trying to reproduce ROOT or R.

At the very least, we'll need to provide blog examples of using Histogrammar with another library that computes statistics to make the error bars. All of these functions are in ROOT and R; they could be the first examples.

**Comment by cranmer** [comment]
I'd definitely separate the plotting. Maybe it's nice to think of the error bar as a separate quantity from the histogram, but with shared definition of how it is computed (eg. the selections and binning) . So that the computation is returning a (histogram, error bar) tuple. One might want to compute all the different error bar options in parallel. Not sure how you have it currently (eg. if the error bars are attributes of the resulting histogram or if it's a separate object)

**Comment by jpivarski** [comment]
The aggregator returns all the sufficient statistics, and the user supplies the calculation that turns it into a plot or a statistical inference. That much is true whether we provide sample calculators or not.

For instance, a

```
Fraction(lambda d: d.trigger > 5, Bin(100, 0, 50, lambda d: d.pt, Count()))
```

accumulates two histograms (`Bin` of `Count`), one with the cut, one without. Histogrammar returns the total counts for all bins, so we can do whatever we need with these raw numbers.

I was in the middle of writing stub functions for drawing plots (my stub functions all draw ASCII art: no dependencies) when I realized we would need a way to turn the raw counts into error bars. The plotting functions take a function that computes an asymmetric error bar from the raw numbers, and right now that function has to be supplied by the user. That's the open question: whether we'd ever provide an easy to plug in sample, so that the user would only have to put `PearsonBinomial` the slot, rather than writing something by hand.

For plotting, I think I should default to no error bars if no such function is provided. I'll add that soon.

**Comment by cranmer** [comment]
Error bars for weighted events will be harder though b/c the interval calculation would in general need to know about the weight for each event. I don't think there are sufficient statistics in that case unless one makes assumptions. That's why I was thinking one might want to be able to essentially attach a lambda to each bin to calculate the intervals.

**Comment by jpivarski** [comment]
I've never seen that generality, but if so, then we'll need to add that to the `Fraction` aggregator. It could accept a lambda to accumulate something in addition to the two copies of its subaggregator, but because any aggregators can be composed, we don't in general know what that subaggregator is. A user attaching a custom lambda function would know, and maybe there's a coupling between the lambda and the choice of subaggregator.

Could you point me to an example of such a calculation? Here are the constraints I'm working with:

  * `Fraction` can accumulate whatever it wants; currently it's accumulating two copies of its subaggregator, named `numerator` and `denominator`.
  * Every input data point has an associated weight >= 0.0. For all functions, weight == 0.0 is exactly equivalent to no data point, weight == 1.0 is unweighted, weight == 2.0 is exactly equivalent to filling with two weight == 1.0 data points, etc. That's just a definition of what I mean by "weight".
  * Whatever subaggregators `Fraction` carries, they must be monoids: they must have an associative `+` (or "merge") operation and a zero value.

So for instance, if I want to accumulate a mean, I could store it as a sum of weights and a sum of values, then later divide the two. The sums are monoids, though the ratio is not. (Actually, I compute the mean in a different, more numerically stable way, but this is an illustration.) Can the new statistic for weighted binomials be expressed as a few monoids that we can post-process?

It may be convenient to know that:

  * Every aggregator accumulates an `entries` (sum of weights), even if that is redundant. Some containers need to weight things by their subaggregators' entries.

To keep `Fraction` simple, I might add this as a new primitive, rather than extending its definition.

**Comment by cranmer** [comment]
See (slides 6,7,8)
http://www-conf.slac.stanford.edu/statisticalissues2012/talks/glen_cowan_slac_4jun12.pdf

Normal ROOT solution to this are the `sumW2` errors of page 7.

More generally, one might actually use observed weights to do some density estimation for the weight distribution. That gets very heavy, but an example of something that needs access to all the individual weights. 

I notice you wrote you assume weight >-0. Is that required? We often have samples with negative weights due to the way some NLO calculations are implemented.

**Comment by jpivarski** [comment]
Okay, I'm a little less worried now: I think we can provide for such things through creative combinations of primitives, and in fact it illustrates the usefulness of this compositional approach.

I should clarify that "weights" in Histogrammar are metadata, something outside the data record itself. If user data has type `T`, then a data point passed through the system has type `(T, Double)` where the second entry is the weight. Early on, I decided against applying all cuts as filter functions, the way Spark et al do, because PAW and ROOT's approach of letting selectors be fuzzy is pretty useful. To track a data point that is "half cut out," I have to carry around a 0.5 somewhere. That's why it's _in addition to_ the user data.

However, if you have some other weight-like quantity that is derived from the data, such as an event weight calculated by a physics Monte Carlo, then you the user would be carrying that value as part of your user data, `T`. You can even have negative weights if you want.

The reason I rejected negative weights was because they cause pathologies in the numerically stable mean and variance calculations I'm using. After having made that decision, it was useful in the algebra to know that total weight == 0.0 means the aggregator is in its initial state.

To be concrete, if your event type `T` has an `mcweight` field, you can compute the sums on page 7 as

```
S1 = Sum(lambda t: t.mcweight)
S2 = Sum(lambda t: t.mcweight**2)
```

and if you wanted a histogram full of them, you'd do

```
hist = Bin(100, 0, 1, lambda t: pt,
           Branch(Sum(lambda t: t.mcweight), Sum(lambda t: t.mcweight**2)))
```

Now the `S1` for bin `50` is `hist.values[50].i0` and the `S2` is `hist.values[50].i1` and you can compute whatever you need.

**Pull request merged**
